### ISSUE TITLE
Main page(display page)

### ISSUE THREAD

**Issue by sapoepsilon** [sapoepsilon/RentaTool#3]
Search box (Just the display)
List of the tools (Just the display)
Picture, name, hardcoded           value of the distance.

**Comment by za01br** [comment]
SPRINT 1 GOAL 🚀
- [ ] Define Grid system based on layout.
- [ ] Add Search Bar (https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/searchbar)
- [ ] Add Title "tools" + Filter btn + Layout btn
- [ ] Create fake data with "Name", "Image", "Price", "Distance"
- [ ] Create card view, 2 cards side-by-side (i.e: https://github.com/devcrux/WeatherApp)
- [ ] Integrate with the DB to query data and display on the screen
-----------------------
ADDITIONAL: 🏆
- [ ] Click event to every card -> when clicked, navigate to "DetailsPage" and display info...
- [ ] Grid view: Add option to change from Grid to List View
- [ ] Add Filters
- [ ] Add search functionality
